version: "3.9"

services:
  app1:
    image: flask_for_varnish:latest
    build:
      context: ./apps/
      dockerfile: Dockerfile
    environment:
      FLASK_PORT: 1234
    ports:
      - "5000:1234"
    volumes:
      - ./apps/:/app/

  app2:
    image: flask_for_varnish:latest
    build:
      context: ./apps/
      dockerfile: Dockerfile
    environment:
      FLASK_PORT: 5678
    ports:
      - "5001:5678"
    volumes:
      - ./apps/:/app/

  varnish:
    image: my_varnish:latest
    build:
      context: ./varnish/
      dockerfile: Dockerfile
    # http://varnish-cache.org/docs/6.0/reference/varnishd.html#feature
    command: "-p feature=+esi_disable_xml_check"
    ports:
      - "8080:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
